apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bellandirangu/backend:v2
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo-0.mongo-service:27017/"
        - name: DB_NAME
          value: "yolomy"
        - name: PORT
          value: "5000"
