version: "3.8"

services:

  frontend:
    image: bellandirangu/frontend:v2
    container_name: yolo-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    image: bellandirangu/backend:v2
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local
